#!/usr/bin/env bash
# This script redirects to another page

sudo apt update -y
sudo apt install nginx -y
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\t rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sudo sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-available/default
sudo service nginx start
