#!/usr/bin/env bash
# Install nginx web server and place it on port 80

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default_1

sudo service nginx restart
