#!/usr/bin/env bash
# This script script that configures an Ubuntu server with a new localhost and add facebook.com
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i '$a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
